export const menswearProducts = [
  {
    name: "Two Strap Leather Biker Boots",
    category: "Footwear",
    image: "/menfoot1.jpeg",
    keywords: "two strap leather biker boots footwear brown black shoes",
  },
  {
    name: "Burgundy Rub-Off Leather Combat Boots",
    category: "Footwear",
    image: "/menfoot2.jpeg",
    keywords: "burgundy rub off leather combat boots footwear shoes",
  },
  {
    name: "Brown Leather Timberland Roll-Top Boots",
    category: "Footwear",
    image: "/menfoot3.jpeg",
    keywords: "brown leather timberland roll top boots footwear shoes",
  },
  {
    name: "Shiny Black Patent Harness Ankle Boots",
    category: "Footwear",
    image: "/menfoot4.jpeg",
    keywords: "shiny black patent harness ankle boots footwear shoes",
  },
  {
    name: "Black Solid Ankle-High Shaft Chelsea Boots",
    category: "Footwear",
    image: "/menfoot5.jpeg",
    keywords: "black solid ankle high shaft chelsea boots footwear shoes",
  },
  {
    name: "Black Leather Moc-Toe Slip-On Loafers",
    category: "Footwear",
    image: "/menfoot6.jpeg",
    keywords: "black leather moc toe slip on loafers footwear shoes",
  },
  {
    name: "Retro Styled White Shoes with Metallic Overlay",
    category: "Footwear",
    image: "/menfoot7.jpeg",
    keywords: "retro styled white shoes metallic overlay footwear sneakers",
  },
  {
    name: "Deconstructed Ripped Suede Mesh Upper Shoes",
    category: "Footwear",
    image: "/menfoot8.jpeg",
    keywords: "deconstructed ripped suede mesh upper shoes footwear",
  },
  {
    name: "Dark Brown Leather Derby Oxford Shoes",
    category: "Footwear",
    image: "/menfoot9.jpeg",
    keywords: "dark brown leather derby oxford shoes footwear formal",
  },
  {
    name: "Brown Plaid Wide-Leg Loose-Fit Casual Trousers",
    category: "Lowerwear",
    image: "/menlow1.jpeg",
    keywords: "brown plaid wide leg loose fit casual trousers lowerwear",
  },
  {
    name: "Dark Wash Blue Denim Jeans with Large White Dragons and Cloud Embroidery",
    category: "Lowerwear",
    image: "/menlow2.jpeg",
    keywords: "dark wash blue denim jeans dragons cloud embroidery lowerwear",
  },
  {
    name: "Relaxed Straight-Leg Cut with Knife Pleat Trousers",
    category: "Lowerwear",
    image: "/menlow3.jpeg",
    keywords: "relaxed straight leg knife pleat trousers lowerwear",
  },
  {
    name: "Pleated Baggy Denim Pants with a Barrel-Leg Silhouette",
    category: "Lowerwear",
    image: "/menlow4.jpeg",
    keywords: "pleated baggy denim pants barrel leg lowerwear",
  },
  {
    name: "Grunge Loose-Fit Denim Jeans",
    category: "Lowerwear",
    image: "/menlow5.jpeg",
    keywords: "grunge loose fit denim jeans lowerwear streetwear",
  },
  {
    name: "Wide-Leg Denim Jeans with Pink Cherry Blossom Graphic Print",
    category: "Lowerwear",
    image: "/menlow6.jpeg",
    keywords: "wide leg denim jeans pink cherry blossom graphic print lowerwear",
  },
  {
    name: "Dark Grey Acid-Wash Baggy Cargo Denim Jeans",
    category: "Lowerwear",
    image: "/menlow7.jpeg",
    keywords: "dark grey acid wash baggy cargo denim jeans lowerwear",
  },
  {
    name: "Streetwear Baggy Fit Jeans with Mid-Rise Waist",
    category: "Lowerwear",
    image: "/menlow8.jpeg",
    keywords: "streetwear baggy fit jeans mid rise waist lowerwear",
  },
  {
    name: "Olive Green, Wide-Leg Baggy Denim Jeans with Washed Finis",
    category: "Lowerwear",
    image: "/menlow9.jpeg",
    keywords: "olive green wide leg baggy denim jeans washed lowerwear",
  },
  {
    name: "Washed Denim Fur Hooded Jacket with Faux-Fur Lining and Hood",
    category: "Outerwear",
    image: "/menout1.jpeg",
    keywords: "washed denim fur hooded jacket faux fur lining outerwear",
  },
  {
    name: "Black Boxy Oversized Faux Leather Jacket with Spread Collar",
    category: "Outerwear",
    image: "/menout2.jpeg",
    keywords: "black boxy oversized faux leather jacket spread collar outerwear",
  },
  {
    name: "Grey Washed Denim Bomber Jacket with Elasticized Waistband",
    category: "Outerwear",
    image: "/menout3.jpeg",
    keywords: "grey washed denim bomber jacket elasticized waistband outerwear",
  },
  {
    name: "Navy Blue and White Letterman-Style Varsity Jacket",
    category: "Outerwear",
    image: "/menout4.jpeg",
    keywords: "navy blue white letterman varsity jacket outerwear",
  },
  {
    name: "Classic Blue Denim Trucker Jacket",
    category: "Outerwear",
    image: "/menout5.jpeg",
    keywords: "classic blue denim trucker jacket outerwear",
  },
  {
    name: "Colorblocked Patchwork Canvas Work Jacket",
    category: "Outerwear",
    image: "/menout6.jpeg",
    keywords: "colorblocked patchwork canvas work jacket outerwear",
  },
  {
    name: "Brown Faux-Suede and Faux-Fur Lined Jacket with Chinese-Knot Buttons",
    category: "Outerwear",
    image: "/menout7.jpeg",
    keywords: "brown faux suede faux fur lined jacket chinese knot buttons outerwear",
  },
  {
    name: "Vintage Style Japanese Souvenir Jacket with Reversible Style",
    category: "Outerwear",
    image: "/menout8.jpeg",
    keywords: "vintage japanese souvenir reversible jacket outerwear",
  },
  {
    name: "Brown Distressed Faux-Leather Bomber Jacket",
    category: "Outerwear",
    image: "/menout9.jpeg",
    keywords: "brown distressed faux leather bomber jacket outerwear",
  },
  {
    name: "Brown and beige Plaid Checked Casual Shirt",
    category: "Upperwear",
    image: "/menup1.jpeg",
    keywords: "brown beige plaid checked casual shirt upperwear",
  },
  {
    name: "Vintage Maroon Marvel Spider-Man Graphic T-shirt",
    category: "Upperwear",
    image: "/menup2.jpeg",
    keywords: "vintage maroon marvel spiderman graphic tshirt upperwear",
  },
  {
    name: "Black and White Pinstripe Short-Sleeve Button-Down Shirt",
    category: "Upperwear",
    image: "/menup3.jpeg",
    keywords: "black white pinstripe short sleeve button down shirt upperwear",
  },
  {
    name: "Dark Navy Blue Long-Sleeve Henley T-shirt with Buttoned Placket",
    category: "Upperwear",
    image: "/henley.jpeg",
    keywords: "dark navy blue long sleeve henley tshirt buttoned placket upperwear",
  },
  {
    name: "Mandarin-Style Embroidered Linen Shirt",
    category: "Upperwear",
    image: "/menup5.jpeg",
    keywords: "mandarin embroidered linen shirt upperwear",
  },
  {
    name: "Short-Sleeve Navy Layered Graphics T-shirt",
    category: "Upperwear",
    image: "/menup6.jpeg",
    keywords: "short sleeve navy layered graphics tshirt upperwear",
  },
  {
    name: "Relaxed-Fit Street Style Long-Sleeve",
    category: "Upperwear",
    image: "/menup7.jpeg",
    keywords: "relaxed fit street style long sleeve upperwear",
  },
  {
    name: "Short-Sleeve Casual Button-down Shirt",
    category: "Upperwear",
    image: "/menup8.jpeg",
    keywords: "short sleeve casual button down shirt upperwear",
  },
  {
    name: "Graphic Polo Shirt with Distressed Fabric",
    category: "Upperwear",
    image: "/menup9.jpeg",
    keywords: "graphic polo shirt distressed fabric upperwear",
  },
  {
    name: "Washed Denim Brown Faux-Suede Baseball Cap",
    category: "Accessories",
    image: "/menac1.jpeg",
    keywords: "washed denim brown faux suede baseball cap accessories",
  },
  {
    name: "Brown Leather Messenger Bag With Flap Front",
    category: "Accessories",
    image: "/menac2.jpeg",
    keywords: "brown leather messenger bag flap front accessories",
  },
  {
    name: "Y2K Aesthetic Layering Necklace Set",
    category: "Accessories",
    image: "/menac3.jpeg",
    keywords: "y2k aesthetic layering necklace set accessories",
  },
  {
    name: "Steampunk Analog Wristwatch with Bronze-Toned Circular Case",
    category: "Accessories",
    image: "/menac4.jpeg",
    keywords: "steampunk analog wristwatch bronze toned circular case accessories",
  },
  {
    name: "Brown Canvas and Leather Shoulder Bag",
    category: "Accessories",
    image: "/menac5.jpeg",
    keywords: "brown canvas leather shoulder bag accessories",
  },
  {
    name: "Multi-Piece Punk Rock Studded Bracelet Set",
    category: "Accessories",
    image: "/menac6.jpeg",
    keywords: "multi piece punk rock studded bracelet set accessories",
  },
  {
    name: "Silver-Toned Chain Necklace Set",
    category: "Accessories",
    image: "/menac7.jpeg",
    keywords: "silver toned chain necklace set accessories",
  },
  {
    name: "6 Piece Gothic Style Metal Ring Set",
    category: "Accessories",
    image: "/menac8.jpeg",
    keywords: "gothic style metal ring set accessories",
  },
  {
    name: "Distressed Brown Leather Belts Sett",
    category: "Accessories",
    image: "/menac9.jpeg",
    keywords: "distressed brown leather belts accessories",
  },
];
