export const womenswearProducts = [
  {
    name: "Brown Strappy Wedge Sandals",
    category: "Footwear",
    image: "/womenfoot1.jpeg",
    keywords: "brown strappy wedge sandals footwear shoes",
  },
  {
    name: "Y2K-Style Chunky Platform Mule Sandals",
    category: "Footwear",
    image: "/womenfoot2.jpeg",
    keywords: "y2k chunky platform mule sandals footwear shoes",
  },
  {
    name: "Suede Platform Heels",
    category: "Footwear",
    image: "/womenfoot3.jpeg",
    keywords: "suede platform heels footwear shoes",
  },
  {
    name: "Brown Leather Chunky Block Heel Knee-High Boots",
    category: "Footwear",
    image: "/womenfoot4.jpeg",
    keywords: "brown leather chunky block heel knee high boots footwear",
  },
  {
    name: "Brown Suede Mary Jane Flats",
    category: "Footwear",
    image: "/womenfoot5.jpeg",
    keywords: "brown suede mary jane flats footwear shoes",
  },
  {
    name: "Vintage Brown Mid Heel Pumps",
    category: "Footwear",
    image: "/womenfoot6.jpeg",
    keywords: "vintage brown mid heel pumps footwear shoes",
  },
  {
    name: "Round Toe Mudd-Pumps",
    category: "Footwear",
    image: "/womenfoot7.jpeg",
    keywords: "round toe mudd pumps footwear shoes",
  },
  {
    name: "Olive Green Leather Clogs with Braided Strap",
    category: "Footwear",
    image: "/womenfoot8.jpeg",
    keywords: "olive green leather clogs braided strap footwear",
  },
  {
    name: "Embossed-Leather Slingback Shoes",
    category: "Footwear",
    image: "/womenfoot9.jpeg",
    keywords: "embossed leather slingback shoes footwear",
  },
  {
    name: "Wedge Ballet Flat Shoes",
    category: "Footwear",
    image: "/womenfoot10.jpeg",
    keywords: "wedge ballet flat shoes footwear",
  },
  {
    name: "White Low-Top Platform Sneakers",
    category: "Footwear",
    image: "/womenfoot11.jpeg",
    keywords: "white low top platform sneakers footwear shoes",
  },
  {
    name: "Slouchy Mid-Calf Boots with Wedge Heel",
    category: "Footwear",
    image: "/womenfoot12.jpeg",
    keywords: "slouchy mid calf boots wedge heel footwear",
  },
  {
    name: "Black Satin Long-Sleeve Top",
    category: "Upperwear",
    image: "/womenup1.jpeg",
    keywords: "black satin long sleeve top upperwear",
  },
  {
    name: "Grey Short-Sleeve Cable-Knit Button-Up Cardigan",
    category: "Upperwear",
    image: "/womenup2.jpeg",
    keywords: "grey short sleeve cable knit button up cardigan upperwear",
  },
  {
    name: "Burgundy Long-Sleeve Y2K Henley Top",
    category: "Upperwear",
    image: "/womenup3.jpeg",
    keywords: "burgundy long sleeve y2k henley top upperwear",
  },
  {
    name: "Layered Vintage-Style Brown Camisole",
    category: "Upperwear",
    image: "/womenup4.jpeg",
    keywords: "layered vintage brown camisole upperwear",
  },
  {
    name: "Bollywood-Style Hand-Embroidered Georgette Tunic",
    category: "Upperwear",
    image: "/bolly.jpeg",
    keywords: "bollywood hand embroidered georgette tunic upperwear",
  },
  {
    name: "White Short-Sleeve Oversized Graphic T-shirt",
    category: "Upperwear",
    image: "/womenup6.jpeg",
    keywords: "white short sleeve oversized graphic tshirt upperwear",
  },
  {
    name: "Y2K Brown Boho Glam Camisole",
    category: "Upperwear",
    image: "/womenup7.jpeg",
    keywords: "y2k brown boho glam camisole upperwear",
  },
  {
    name: "Distressed Acid-Washed Black Oversized T-Shirt",
    category: "Upperwear",
    image: "/womenup8.jpeg",
    keywords: "distressed acid washed black oversized tshirt upperwear",
  },
  {
    name: "Black and White Striped Sweetheart-Neck Top",
    category: "Upperwear",
    image: "/womenup9.jpeg",
    keywords: "black white striped sweetheart neck top upperwear",
  },
  {
    name: "Y2K Brown Low-Rise Skirt",
    category: "Lowerwear",
    image: "/womenlow1.jpeg",
    keywords: "y2k brown low rise skirt lowerwear",
  },
  {
    name: "Brown Wide-Wale Corduroy Super-Flare Pants",
    category: "Lowerwear",
    image: "/womenlow2.jpeg",
    keywords: "brown wide wale corduroy super flare pants lowerwear",
  },
  {
    name: "Floral-Printed Mermaid Skirt with Asymmetrical Ruffled Hem",
    category: "Lowerwear",
    image: "/womenlow3.jpeg",
    keywords: "floral printed mermaid skirt asymmetrical ruffled hem lowerwear",
  },
  {
    name: "Dark Wash Flared Denim Jeans featuring Floral Embroidery",
    category: "Lowerwear",
    image: "/womenlow4.jpeg",
    keywords: "dark wash flared denim jeans floral embroidery lowerwear",
  },
  {
    name: "Vintage Charcoal-Grey Denim Midi Skirt",
    category: "Lowerwear",
    image: "/womenlow5.jpeg",
    keywords: "vintage charcoal grey denim midi skirt lowerwear",
  },
  {
    name: "High-Waist Denim Fishtail Midi Skirt",
    category: "Lowerwear",
    image: "/womenlow6.jpeg",
    keywords: "high waist denim fishtail midi skirt lowerwear",
  },
  {
    name: "Y2K Low-Rise Blue Denim Jeans",
    category: "Lowerwear",
    image: "/womenlow7.jpeg",
    keywords: "y2k low rise blue denim jeans lowerwear",
  },
  {
    name: "Brown Wide-Leg Trousers featuring a Folded High Waistband",
    category: "Lowerwear",
    image: "/womenlow8.jpeg",
    keywords: "brown wide leg trousers folded high waistband lowerwear",
  },
  {
    name: "Brown Corduroy Wide-Leg Trousers with a Low-Rise Waist",
    category: "Lowerwear",
    image: "/womenlow9.jpeg",
    keywords: "brown corduroy wide leg trousers low rise waist lowerwear",
  },
  {
    name: "Grey Shearling and Leather Double-Breasted Winter Coat",
    category: "Outerwear",
    image: "/womenout1.jpeg",
    keywords: "grey shearling leather double breasted winter coat outerwear",
  },
  {
    name: "Black Bomber Jacket",
    category: "Outerwear",
    image: "https://images.unsplash.com/photo-1551028719-00167b16eac5?auto=format&fit=crop&w=1000&q=85",
    keywords: "black bomber jacket outerwear",
  },
  {
    name: "Brown Oversized Trench Overcoat",
    category: "Outerwear",
    image: "/shakira.jpeg",
    keywords: "brown oversized trench overcoat outerwear",
  },
  {
    name: "Brown Fur-Trim Shearling Jacket",
    category: "Outerwear",
    image: "/womenout3.jpeg",
    keywords: "brown fur trim shearling jacket outerwear",
  },
  {
    name: "Y2K Brown and Green Gradient Knit Cardigan",
    category: "Outerwear",
    image: "/womenout4.jpeg",
    keywords: "y2k brown green gradient knit cardigan outerwear",
  },
  {
    name: "Brown Faux-Suede Jacket",
    category: "Outerwear",
    image: "/womenout5.jpeg",
    keywords: "brown faux suede jacket outerwear",
  },
  {
    name: "Open Crochet Tie-Front Cardigan with V-neckline",
    category: "Outerwear",
    image: "/womenout6.jpeg",
    keywords: "open crochet tie front cardigan v neckline outerwear",
  },
  {
    name: "Dark Wash Denim Cape Jacket",
    category: "Outerwear",
    image: "/womenout7.jpeg",
    keywords: "dark wash denim cape jacket outerwear",
  },
  {
    name: "Brown Distressed Leather Moto Jacket with Stand Collar",
    category: "Outerwear",
    image: "/womenout8.jpeg",
    keywords: "brown distressed leather moto jacket stand collar outerwear",
  },
  {
    name: "Grey Cable-Knit V-neck Button-Down Cardigan with Dropped Shoulders",
    category: "Outerwear",
    image: "/womenout9.jpeg",
    keywords: "grey cable knit v neck button down cardigan dropped shoulders outerwear",
  },
  {
    name: "Faux Suede and Faux-Fur Winter Jacket",
    category: "Outerwear",
    image: "/womenout10.jpeg",
    keywords: "faux suede faux fur winter jacket outerwear",
  },
  {
    name: "Y2K Styled Babydoll Cardigan Hoodie",
    category: "Outerwear",
    image: "/womenout11.jpeg",
    keywords: "y2k styled babydoll cardigan hoodie outerwear",
  },
  {
    name: "Brown Crochet Fringed Scarf",
    category: "Accessories",
    image: "/women1.jpeg",
    keywords: "brown crochet fringed scarf accessories",
  },
  {
    name: "Chandelier Earrings",
    category: "Accessories",
    image: "/women2.jpeg",
    keywords: "chandelier earrings accessories jewellery",
  },
  {
    name: "Woollen Check Scarf",
    category: "Accessories",
    image: "/women3.jpeg",
    keywords: "woollen check scarf accessories",
  },
  {
    name: "Handcrafted wire-wrapped Link Bracelet",
    category: "Accessories",
    image: "/women4.jpeg",
    keywords: "handcrafted wire wrapped link bracelet accessories",
  },
  {
    name: "Vintage Brown Shoulder Bag",
    category: "Accessories",
    image: "/women5.jpeg",
    keywords: "vintage brown shoulder bag accessories handbag",
  },
  {
    name: "Silver Multi-Layered Charm Strand Necklace",
    category: "Accessories",
    image: "/women6.jpeg",
    keywords: "silver multi layered charm strand necklace accessories jewellery",
  },
  {
    name: "Dome-Shaped Drop Earrings",
    category: "Accessories",
    image: "/women7.jpeg",
    keywords: "dome shaped drop earrings accessories jewellery",
  },
  {
    name: "Hand-Tooled Leather Shoulder Bag",
    category: "Accessories",
    image: "/women8.jpeg",
    keywords: "hand tooled leather shoulder bag accessories handbag",
  },
  {
    name: "Vintage Antique-Style Pendant Necklaces",
    category: "Accessories",
    image: "/womenac9.jpeg",
    keywords: "vintage antique style pendant necklaces accessories jewellery",
  },
  {
    name: "Oxidised Silver Cuff Bracelet",
    category: "Accessories",
    image: "/womenac10.jpeg",
    keywords: "oxidised silver cuff bracelet accessories jewellery",
  },
  {
    name: "Wide Boho Disc-Belt",
    category: "Accessories",
    image: "/womenac11.jpeg",
    keywords: "wide boho disc belt accessories",
  },
  {
    name: "Y2K Stackable 7 Piece Ring Set",
    category: "Accessories",
    image: "/womenac12.jpeg",
    keywords: "y2k stackable seven piece ring set accessories jewellery",
  },
];
